global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: [
          'logrus-service:8080',
          'zap-service:8080',
          'zero-service:8080',
          'stdlib-service:8080'
      ]